// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cveref is the predicate function for cveref builders.
type Cveref func(*sql.Selector)

// Object is the predicate function for object builders.
type Object func(*sql.Selector)

// Oval is the predicate function for oval builders.
type Oval func(*sql.Selector)

// State is the predicate function for state builders.
type State func(*sql.Selector)

// Test is the predicate function for test builders.
type Test func(*sql.Selector)
