// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ct_oval_tool/pkg/ent/cveref"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Cveref is the model entity for the Cveref schema.
type Cveref struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RefID holds the value of the "ref_id" field.
	RefID string `json:"ref_id,omitempty"`
	// RefURL holds the value of the "ref_url" field.
	RefURL       string `json:"ref_url,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Cveref) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cveref.FieldID:
			values[i] = new(sql.NullInt64)
		case cveref.FieldRefID, cveref.FieldRefURL:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Cveref fields.
func (c *Cveref) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cveref.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case cveref.FieldRefID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ref_id", values[i])
			} else if value.Valid {
				c.RefID = value.String
			}
		case cveref.FieldRefURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ref_url", values[i])
			} else if value.Valid {
				c.RefURL = value.String
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Cveref.
// This includes values selected through modifiers, order, etc.
func (c *Cveref) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// Update returns a builder for updating this Cveref.
// Note that you need to call Cveref.Unwrap() before calling this method if this Cveref
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Cveref) Update() *CverefUpdateOne {
	return NewCverefClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Cveref entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Cveref) Unwrap() *Cveref {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Cveref is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Cveref) String() string {
	var builder strings.Builder
	builder.WriteString("Cveref(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("ref_id=")
	builder.WriteString(c.RefID)
	builder.WriteString(", ")
	builder.WriteString("ref_url=")
	builder.WriteString(c.RefURL)
	builder.WriteByte(')')
	return builder.String()
}

// Cverefs is a parsable slice of Cveref.
type Cverefs []*Cveref
