// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ct_oval_tool/pkg/ent/cveref"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CverefCreate is the builder for creating a Cveref entity.
type CverefCreate struct {
	config
	mutation *CverefMutation
	hooks    []Hook
}

// SetRefID sets the "ref_id" field.
func (cc *CverefCreate) SetRefID(s string) *CverefCreate {
	cc.mutation.SetRefID(s)
	return cc
}

// SetRefURL sets the "ref_url" field.
func (cc *CverefCreate) SetRefURL(s string) *CverefCreate {
	cc.mutation.SetRefURL(s)
	return cc
}

// Mutation returns the CverefMutation object of the builder.
func (cc *CverefCreate) Mutation() *CverefMutation {
	return cc.mutation
}

// Save creates the Cveref in the database.
func (cc *CverefCreate) Save(ctx context.Context) (*Cveref, error) {
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CverefCreate) SaveX(ctx context.Context) *Cveref {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CverefCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CverefCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CverefCreate) check() error {
	if _, ok := cc.mutation.RefID(); !ok {
		return &ValidationError{Name: "ref_id", err: errors.New(`ent: missing required field "Cveref.ref_id"`)}
	}
	if _, ok := cc.mutation.RefURL(); !ok {
		return &ValidationError{Name: "ref_url", err: errors.New(`ent: missing required field "Cveref.ref_url"`)}
	}
	return nil
}

func (cc *CverefCreate) sqlSave(ctx context.Context) (*Cveref, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CverefCreate) createSpec() (*Cveref, *sqlgraph.CreateSpec) {
	var (
		_node = &Cveref{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(cveref.Table, sqlgraph.NewFieldSpec(cveref.FieldID, field.TypeInt))
	)
	if value, ok := cc.mutation.RefID(); ok {
		_spec.SetField(cveref.FieldRefID, field.TypeString, value)
		_node.RefID = value
	}
	if value, ok := cc.mutation.RefURL(); ok {
		_spec.SetField(cveref.FieldRefURL, field.TypeString, value)
		_node.RefURL = value
	}
	return _node, _spec
}

// CverefCreateBulk is the builder for creating many Cveref entities in bulk.
type CverefCreateBulk struct {
	config
	err      error
	builders []*CverefCreate
}

// Save creates the Cveref entities in the database.
func (ccb *CverefCreateBulk) Save(ctx context.Context) ([]*Cveref, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Cveref, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CverefMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CverefCreateBulk) SaveX(ctx context.Context) []*Cveref {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CverefCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CverefCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
