// Code generated by ent, DO NOT EDIT.

package cveref

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the cveref type in the database.
	Label = "cveref"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRefID holds the string denoting the ref_id field in the database.
	FieldRefID = "ref_id"
	// FieldRefURL holds the string denoting the ref_url field in the database.
	FieldRefURL = "ref_url"
	// Table holds the table name of the cveref in the database.
	Table = "cverefs"
)

// Columns holds all SQL columns for cveref fields.
var Columns = []string{
	FieldID,
	FieldRefID,
	FieldRefURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Cveref queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRefID orders the results by the ref_id field.
func ByRefID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefID, opts...).ToFunc()
}

// ByRefURL orders the results by the ref_url field.
func ByRefURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefURL, opts...).ToFunc()
}
